### ISSUE TITLE
`Build-And-Deploy-Tenant-K8s-resources` failed

### ISSUE THREAD

**Issue by cfregly** [aws-samples/aws-saas-factory-eks-saas-workshop#2]
Hi there!

I'm following the silo-tenant instructions and i am hitting this...

![image](https://user-images.githubusercontent.com/1438064/144735088-164c2291-5fe1-4ed9-a410-5364d73685e8.png)

![image](https://user-images.githubusercontent.com/1438064/144694894-426a6c98-1fc9-439d-963d-e52c2a47f370.png)

...any ideas?

**Comment by cfregly** [comment]
i followed the instructions here and it works:  https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture

**Comment by tobuck-aws** [comment]
@cfregly there are two distinct repos here. This is the workshop for EKS SaaS, and while loosely related related to the [EKS SaaS reference architecture](https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture), it is different. The narrative (and all directions) for this workshop [can be found here](https://catalog.us-east-1.prod.workshops.aws/v2/workshops/e04c0885-830a-479b-844b-4c7af79697f8/en-US). So you're good to go now?

**Comment by cfregly** [comment]
Yup, I’m good, but still wondering why the workshop didn’t work for me.  Any known issues?

Let me know if I can provide any more info.  Otherwise, we can chalk this up to user error and close this.

Thanks!
