### ISSUE TITLE
Error in package.json prevents k8 image building of shared services (Fix enclosed)

### ISSUE THREAD

**Issue by lspellman** [aws-samples/aws-saas-factory-eks-saas-workshop#3]
the file /aws-saas-factory-eks-saas-workshop/services/shared/package.json

has an error at line 31. It reads:

    "@aws-sdk/util-dynamodb@": "^3.18.0",

(note the @ sign after dynamodb) and should be:

    "@aws-sdk/util-dynamodb": "^3.18.0",

This prevents the following workshop step in Lab 1, core microservices, from building the k8s images correctly:

cd ~/environment/aws-saas-factory-eks-saas-workshop/
./scripts/deploy-tenant-registration.sh

**Comment by tobuck-aws** [comment]
Thank you! Fixed.
