### ISSUE TITLE
wrong path for idp.service.ts

### ISSUE THREAD

**Issue by cfregly** [aws-samples/aws-saas-factory-eks-saas-workshop#39]
<img width="911" alt="image" src="https://user-images.githubusercontent.com/1438064/188473985-c1080d63-831e-425d-927a-b5907c501fb7.png">

<img width="899" alt="image" src="https://user-images.githubusercontent.com/1438064/188474235-ad8dd468-eb58-42b5-a401-994fc8afe7de.png">

 => ```services/apps/shared/...```

**Comment by tobuck-aws** [comment]
Fixed
