### ISSUE TITLE
Container image build for user-management fails due to changes to main.ts (probable fix enclosed)

### ISSUE THREAD

**Issue by lspellman** [aws-samples/aws-saas-factory-eks-saas-workshop#5]
Context:  workshop lab 1, core microservices, step 12 - build and deploy remaining shared services

when ./scripts/deploy-user-management.sh runs, it fails with the following:

> ERROR in apps/user-management/src/main.ts:25:20
> TS2554: Expected 0 arguments, but got 1.
>     23 |     options,
>     24 |   );
>   > 25 |   await app.listen(() => {
>        |                    ^^^^^^^
>   > 26 |     console.log('Users microservice is listening...');
>        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> /*
>   > 27 |   });
>        | ^^^^
>     28 | }
>     29 | bootstrap();
>     30 |

In the original commit for this file, the relevant code at line 25 was only:

`await app.listen(3000);`

I updated my version of the file to:

`await app.listen();       // assume that port defined in options block where it is defined as 3015 will take care of port assignment`

With that, the build was successful and the user-management image was loaded to the repo. I don't know if my interpretation of the fix is appropriate. I'll press on from here.

EDIT: Yes, this appeared to work fine. Pod deployed running on port 3015 as expected. This looks to be a valid fix.

**Comment by tobuck-aws** [comment]
@lspellman thanks for the feedback, and so sorry for the troubles! I just looked through [Nest's code](https://github.com/nestjs/nest/blob/f90af4911de28cdaf527d17355c8d5e335afab64/packages/common/interfaces/nest-microservice.interface.ts), and this was a breaking change between version 7 and 8. We'll work on getting a build setup to catch silliness like this in the future. Apologies again.

In the interim, I'll commit your fix. Also, please feel free to PR any of these changes you come across. Happy to accept your input.

**Comment by lspellman** [comment]
No problem Toby, I've enjoyed digging into it. I did the workshop at Re:Invent but didn't have time to go deep. So I knew it "worked" fairly recently and that some things must have changed in the interim.  I completed it earlier today, and am preparing some presentations for internal teams and customers.

**Comment by tobuck-aws** [comment]
Oh, nice. Thanks for the note! Happy to entertain suggestions.
