### ISSUE TITLE
This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version. (Cloud assembly schema version mismatch: Maximum schema version supported is 14.0.0, but found 16.0.0)

### ISSUE THREAD

**Issue by jimini55** [aws-samples/aws-saas-factory-eks-saas-workshop#6]
Hi,

I encountered an error in step of Lab 0 (https://catalog.us-east-1.prod.workshops.aws/v2/workshops/e04c0885-830a-479b-844b-4c7af79697f8/en-US/lab-0/2-on-your-own/8-create-cluster)

_This CDK CLI is not compatible with the CDK library used by your application. Please upgrade the CLI to the latest version.
(Cloud assembly schema version mismatch: Maximum schema version supported is 14.0.0, but found 16.0.0)_

I tried this workaround and it worked well. 

```
cd ../..
npm uninstall -g aws-cdk
npm install -g aws-cdk@latest
source ./ON-YOUR-OWN-deploy-eks.sh
```

I'm leaving this comment for others' information. Hope this CDK version mismatch issue fixed soon.

**Comment by jimini55** [comment]
Team, one more thing to add: 

the workshop seems to use the same cluster name as EKS Workshop - "eksworkshop-eksctl".
It conflicts if there is one already - so why don't you give the cluster a unique name in the template? thanks!

**Comment by ranjith-aws** [comment]
@jimini55 Thanks for posting the issue. We will take a look at this.
