### ISSUE TITLE
Amazon EKS Kubernetes versions 1.21 Not supported anymore

### ISSUE THREAD

**Issue by reynanvalencia** [aws-samples/aws-saas-factory-eks-saas-workshop#85]
Kindly update the Kubernetes version. 1_21 version is not supported anymore.

Available Amazon EKS Kubernetes versions (as of this writing)
The following Kubernetes versions are currently available for new Amazon EKS clusters:
- 1.25
- 1.24
- 1.23
- 1.22

https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#available-versions

**Comment by ranjith-aws** [comment]
Thanks for notifying. We are pushing an update for this shortly.
